package net.anotheria.anoprise.eventservice;

public interface RemoteEventChannelSupportFactory {
	RemoteEventChannelConsumerProxy createRemoteEventChannelConsumerProxy(String channelName);
	RemoteEventChannelSupplierProxy createRemoteEventChannelSupplierProxy(String channelName);
}
